### ISSUE TITLE
Bài 03 Nhóm các individual action từ mục pages để tạo ra các steps 

### ISSUE THREAD

**Issue by thienphuong** [hahh2/selenium-amabuy#3]
Trong mục **pages** có [LoginPage.java](https://github.com/hahh2/selenium-amabuy/blob/master/src/test/java/vn/amabuy/pages/LoginPage.java). Trong này chứa các individual action ( tương tác đơn lẻ) trên từng phần tử

```
	public void enterEmailOrPhoneNumber(String keyword) {
		userId.sendKeys(keyword);
	}
```

và 

```
	public void enterPassword(String keyword) {
		passWordId.sendKeys(keyword);
	}
```

Từ đây tạo một class trong mục **steps** trong này ta sẽ viết hàm login như dưới đây

**Comment by thienphuong** [comment]
```
    LoginPage onLoginPage;

    @Step
    public void enter_email_or_phone(String emailOrPhone){

        onLoginPage.enterEmailOrPhoneNumber(emailOrPhone);
    }

    @Step
    public void enter_password(String password){
        
        onLoginPage.enterPassword(password);
    }

    @Step
    public void login_applicatioin(String emailOrPhone, String password){

        onLoginPage.enterEmailOrPhoneNumber(emailOrPhone);
        onLoginPage.enterPassword(password);
    }
```

**Comment by hahh2** [comment]
Cho m hỏi hàm thứ 3 sao không gọi 
  @Step
    public void login_applicatioin(String emailOrPhone, String password){

        enter_email_or_phone(emailOrPhone);
        enter_password(password);
    }

**Comment by hahh2** [comment]
https://github.com/hahh2/selenium-amabuy/tree/master/src/test/java/vn/amabuy/steps

**Comment by thienphuong** [comment]
Mình có thể gộp vào cũng được, không gộp mà tách từng step cũng được. không sao cả, do cách mình  tổ chức.

Sau này nó liên quan tới phần report. Nếu viết gộp lại thì report nó sẽ cô đọng hơn. Ít steps được in ra trên reports, Khó khăn trong việc debug cho tìm lỗi.

Sau khi viết được một đoạn mã hoàn chỉnh. Dựa trên report sẽ phân tích vấn đề này lúc đó mới có cái nhìn trực quan
