### ISSUE TITLE
Bài 04: Review kết quả bài tập 03

### ISSUE THREAD

**Issue by thienphuong** [hahh2/selenium-amabuy#4]
[LoginSteps.java](https://github.com/hahh2/selenium-amabuy/blob/master/src/test/java/vn/amabuy/steps/LoginSteps.java)

- Không cần phải `extends LoginPage` 
- Không cần phải khai báo và khởi tạo đối tượng từ **LoginPage**
- Dòng code thứ 29 thiếu _access modifier_ **public** 
```
	@Step void remember_on_brower() {
		click_remember_on_checkbox();
	}
```

**Comment by thienphuong** [comment]
```
	@Step
	public void click_remember_on_checkbox() {
		loginPage.clickRememberCheckbox();
	}
	
	@Step void remember_on_brower() {
		click_remember_on_checkbox();
	}
```

Không cần phải viết phương thức (method) `remember_on_brower()` vì bên trong nó **chỉ** gọi tới có **một** action là. 

Chỉ viết thêm những method kiểu giống như này khi nó có **chứa nhiều hơn 1 action** để tạo thành một luồng nghiệp vụ chứa một nhóm các steps liên quan

Ví dụ với luồng login vào hệ thống cần ít nhất 3 steps là 
- điền email
- điền mật khẩu
- click vào nút login

Lúc đó mới cần nhóm 3 hành động đơn này thành một nhóm để tạo nên luồng nghiệp vụ.

**Comment by thienphuong** [comment]
Đoạn code mong đợi sẽ là

```
package vn.amabuy.steps;
import net.thucydides.core.annotations.Step;

public class LoginSteps {
	LoginPage onLoginPage;

	@Step
	public void enter_email_or_phonenumber(String emailOrPhoneNumber) {
		onLoginPage.enterEmailOrPhoneNumber(emailOrPhoneNumber);
	}
	
	@Step
	public void enter_password(String passWord) {
		onLoginPage.enterPassword(passWord);
	}
	
	@Step
	public void enter_on_brower(String emailOrPhoneNumber, String password) {
		enter_email_or_phonenumber(emailOrPhoneNumber);
		enter_password(password);
                click_btn_login();
	}
	
	@Step
	public void click_btn_login() {
		onLoginPage.clickButtonLogin();
	}
}

```

**Comment by hahh2** [comment]
Em gửi lại

https://github.com/hahh2/selenium-amabuy/tree/master/src/test/java/vn/amabuy/steps

**Comment by hahh2** [comment]
package vn.amabuy.steps;
import net.thucydides.core.annotations.Step;
import vn.amabuy.pages.*;

public class LoginSteps{
	LoginPage onLoginPage = new LoginPage();
	@Step
	public void enter_email_or_phonenumber(String emailOrPhoneNumber) {
		
		onLoginPage.enterEmailOrPhoneNumber(emailOrPhoneNumber);
	}
	
	@Step
	public void enter_password(String passWord) {
		onLoginPage.enterPassword(passWord);
	}
	
	@Step
	public void click_remember_on_checkbox() {
		onLoginPage.clickRememberCheckbox();
	}
	
	@Step
	public void click_btn_login() {
		onLoginPage.clickButtonLogin();
	}

	
	@Step
	
	public void enter_on_brower(String emailOrPhoneNumber, String password) {
		enter_email_or_phonenumber(emailOrPhoneNumber);
		enter_password(password);
		click_btn_login();
	}
}

**Comment by hahh2** [comment]
https://github.com/hahh2/selenium-amabuy/blob/master/selenium-amabuy/src/test/java/vn/amabuy/steps/LoginSteps.java
